[WORKER FATAL ERROR] [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/mmarcel3/CRAB.OLD/src/crab/cli/orchestrator.py", line 55, in run_from_cli
    with open(config_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
[WORKER FATAL ERROR] [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/mmarcel3/CRAB.OLD/src/crab/cli/orchestrator.py", line 55, in run_from_cli
    with open(config_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
[WORKER FATAL ERROR] [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/mmarcel3/CRAB.OLD/src/crab/cli/orchestrator.py", line 55, in run_from_cli
    with open(config_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
srun: error: lrdn3364: task 2: Exited with exit code 1
srun: error: lrdn3365: task 3: Exited with exit code 1
srun: error: lrdn3363: task 1: Exited with exit code 1
[WORKER FATAL ERROR] [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
Traceback (most recent call last):
  File "/leonardo/home/userexternal/mmarcel3/CRAB.OLD/src/crab/cli/orchestrator.py", line 55, in run_from_cli
    with open(config_file, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/leonardo/home/userexternal/mmarcel3/CRAB.OLD/config.json'
srun: error: lrdn3361: task 0: Exited with exit code 1
